### ISSUE TITLE
Feature request: Contact groups

### ISSUE THREAD

**Issue by gaalexandre** [StatusCakeDev/terraform-provider-statuscake#46]
It would be great if we could also configure contact groups with this provider.

**Comment by yld** [comment]
You can already use `contact_group` (singular) which is an array of strings https://www.terraform.io/docs/providers/statuscake/r/test.html#contact_group

**Comment by damscott** [comment]
I think @alexandreFre wants the ability to _create_ contact groups.

**Comment by avivek** [comment]
Is there a tentative time when we can expect to see this feature.

**Comment by marceloboeira** [comment]
@gaalexandre @yld @damscott @avivek @plumcraft @jay-lark FYI

I'm currently in need of a terraform providers that supports `integration_id` with contact groups, not only to manage them but to also manage the integrations (PagerDuty, Slack,...). This entire provider points to API v0 which doesn't support that. API V1 seems to support it... since it is very unlikely it will happen soon, given that the issues here are quite old and have no reply, I have built a small "complementary" plugin that supports API V1 Contact Groups management. 

Repo: https://github.com/marceloboeira/terraform-provider-statuscake
Registry: https://registry.terraform.io/providers/marceloboeira/statuscake

**Comment by G-Rath** [comment]
@marceloboeira thanks, will do - I've been thinking the exact same thing about the quality of the documentation; it seems weirdly out of date and lackluster in key places, but have managed to get there in the end (the latest and I think most annoying sadness that I've overcome was how `TypeList` doesn't support defaults, which is why `status_codes` is empty by default for `uptime_test`s).

The heavy use of `interface` and type-casting I think more because of Go lacking generics, so hopefully we'll get better types now that [generics have been accepted](https://github.com/golang/go/issues/43651)

**Comment by marceloboeira** [comment]
> the latest and I think most annoying sadness that I've overcome was how TypeList doesn't support defaults, which is why status_codes is empty by default for uptime_tests).

Yes, TypeList lack of default is annoying, besides that there is also some inconsistent things sometimes, when it saves `[]` as `null` on TF state... 
On top of all of that, statuscake API (even the v1.0.0) is far from ideal... hopefully they release integrations API and make things easier, but even as of now there are some weird API behaviours... 

> The heavy use of interface and type-casting I think more because of Go lacking generics, so hopefully we'll get better types now that generics have been accepted

true, just annoying that given this GRPC behaviour they basically need to do that on a strongly typed language, putting everything as an `interface` just ruins half of go's reliability. I mean, the schema helps to keep things consistent somehow for the primitive types but the more complex ones (e.g.: List/Set/Object...) end up being full of surprises and typecastings, to say the least.

**Comment by G-Rath** [comment]
I've just published `ackama/statuscake` to the Terraform registry: https://registry.terraform.io/providers/ackama/statuscake/latest

It should be good to go as is with both `uptime_test` & `contact_group` - feel free to report bugs and feature requests on the repo.

Currently I plan to make a `page_test` resource and probably a `status_codes` data source to let you do things like `data.status_codes.all`, `data.status_codes.4xx, `data.status_codes.2xx` etc (pretty sure I can't actually have attributes named like that, but I'll think of something).
