### ISSUE TITLE
statuscake_uptime_check.trigger_rate does not take effect initially on create

### ISSUE THREAD

**Issue by nodesocket** [StatusCakeDev/terraform-provider-statuscake#95]
`statuscake_uptime_check.http_check.trigger_rate` does not apply on initial create. I have to `terraform apply` again and then it sees the change:

```
      ~ trigger_rate   = 4 -> 0
```

Setting using:

```
  trigger_rate   = 0
```

Even though I am setting the trigger rate to 0, it defaults to 4 until `terraform apply` is called again. Running latest version of this module `2.0.4`.

**Comment by tomasbasham** [comment]
Thanks for reporting this. It appears not to be a bug with the provider but with a default value within our database forcing this to be a value other than 0 even when specified. We'll look to get this fixed shortly.

Annoyingly because Go treats 0 as the zero-value of an integer (obviously), and the `trigger_rate` field being optional, Terraform cannot determine the difference between 0 having been set explicitly or whether this is the default value and therefore is not being sent to the API, causing the default in the database to be set (which is different from 0).

**Comment by tomasbasham** [comment]
It has not yet been published. We intend to do so shortly

**Comment by nodesocket** [comment]
@tomasbasham ok thanks. Can you ping this issue when it is pushed and live?

**Comment by tomasbasham** [comment]
This change has been published to v2.0.5
